name: Docker image buildx and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: buildx image
      #   run: |
      #     docker buildx create --name mybuilder --use
      #     docker buildx ls
      #     docker buildx --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 yingying6/flask-redis:latest .
      # - name: list docker image
      #   run: docker image ls
      # # docker login
      # - name: dockerhub login
      #   run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      # - name: push to dockerhub
      #   run: docker image push yingying6/flask-redis:latest